# Generated by Django 5.0.7 on 2024-07-24 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Phone number'),
        ),
    ]
