# Generated by Django 5.0.7 on 2024-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_ad_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='publications_images', verbose_name='Photo'),
        ),
    ]
