# Generated by Django 5.0.7 on 2024-07-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_ad_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('see_no_moderate_ads', 'Can see no moderate ads'), ('approve_ad', 'Can approve ad'), ('reject_ad', 'Can reject ad')]},
        ),
    ]
