# Generated by Django 5.0.7 on 2024-07-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_ad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('see_no_moderate_ads', 'Can see no moderate ads')]},
        ),
    ]
